MyOrg/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>logo__c</fullName>
        <label>logo</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tackfield__c</fullName>
        <displayFormat>t-{0000}</displayFormat>
        <label>tackfield</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

MyOrg/src/objects/Devices__c.object
<CustomObject>
    <fields>
        <fullName>DevicceId__c</fullName>
        <label>DeviceId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Devices</label>
    <nameField>
        <displayFormat>DV-{0000}</displayFormat>
        <label>Devices Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/objects/Products__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Products</label>
    <nameField>
        <displayFormat>pd-{0000}</displayFormat>
        <label>Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/classes/deviceData.cls
@RestResource(urlMapping='/deviceData/*')
global with Sharing class deviceData {

  
  @HttpPost
  global static String  doPost(){
    RestRequest req = RestContext.request; 
  //    System.debug('>>>>>>>>>>>>>>>>> ');
   Blob body = req.requestBody;
String bodyString = body.toString();
  System.debug('>>>>>>>>>>>>>>>>> ');
 String name;
String company;
//eg. String body = '{"name" : "Michael", "company" : "Sonoma Partners"}';

JSONParser parser = JSON.createParser(bodyString );
while (parser.nextToken() != null) {
  if ((parser.getCurrentToken() == JSONToken.FIELD_NAME)) {
    String fieldName = parser.getText();
    parser.nextToken();
    if (fieldName == 'deviceid') {
      name = parser.getText();
    } 
  }
}

System.debug('>>>>>> '+name);

    // System.debug(ActivityID_List);
    List<Devices__c> devices = [select id,DevicceId__c from Devices__c where DevicceId__c=:name limit 1];
    if(devices.size() == 0){
    Devices__c d = new Devices__c();
    d.DevicceId__c = name;
    insert d;
    }
    return 'success';
// return  [select id,tackfield__c,name,logo__c,(select name, Name__c,  Price__c from Products__r) from Account where    tackfield__c=:name];
  }
  
  


}