MyOrg/src/objects/Alltricks_deals__c.object
<CustomObject>
    <fields>
        <fullName>Deal_created_On__c</fullName>
        <label>Deal_created_On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Deal_description__c</fullName>
        <label>Deal_description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deal_from__c</fullName>
        <label>Deal_from</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flipkart</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>SnapDeal</fullName>
                </value>
                <value>
                    <fullName>Abof</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal_image_url__c</fullName>
        <label>Deal_image_url</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deal_name__c</fullName>
        <label>Deal_name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Alltricks_deals</label>
    <nameField>
        <displayFormat>Dl-{00000}</displayFormat>
        <label>Alltricks_deals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alltricks_deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/objects/Partner_request__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Partner_request</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Partner_request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/classes/MyRestResource.cls
@RestResource(urlMapping='/samplerest/*')
global with sharing class MyRestResource {
    @HttpGet
    global static void getRecord() {
    
        // Add your code
        
        RestRequest request = RestContext.request;

        System.debug('=====================> '+request.params.get('iid'));
        
       // HttpResponse res = new HttpResponce();
        //res.header('Access-Control-Allow-Origin', '*')
        //res.setBody([select id,name from Account]);
        RestContext.response.addHeader('Access-Control-Allow-Origin', '*');
        String name = RestContext.request.params.get('name');
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize([select id,name,Deal_created_On__c,Deal_description__c,Deal_from__c,Deal_image_url__c,Deal_name__c,Price__c from Alltricks_deals__c]));

        
       // return res;
    }
    
    
    
     @HttpPost
    global static void savePr() {
    RestRequest request = RestContext.request;
    Blob prdata =     request.requestBody;
   
    try{
         System.debug('>>>request   '+request );
        RestContext.response.addHeader('Access-Control-Allow-Origin', '*');
        RestContext.response.addHeader('Access-Control-Allow-Methods', 'POST');
        
      //   JSONParser parser = JSON.createParser(String.valueOf(prdata) );

        
       //  Partner_request__c inv = ;
    PRparser pr =    PRparser.parse(prdata.toString());
       
         Partner_request__c inv = new Partner_request__c ();
       inv.First_Name__c =  pr.First_Name;
       inv.Email__c = pr.Email;
         
    insert inv;
        
       RestContext.response.responseBody =   Blob.valueof(String.valueOf(inv ));
         }catch(exception ex){
         
          RestContext.response.responseBody =  Blob.valueof(String.valueOf(ex.getMessage()));
         }
    }
    
    
    
    
}