MyOrg/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/objects/Partner_request__c.object
<CustomObject>
    <fields>
        <fullName>Accoutn_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accoutn Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Acceptence__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Acceptence</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner_requests</relationshipLabel>
        <relationshipName>Partner_requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Duplicate Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Of_Organization__c</fullName>
        <label>Form Of Organization</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>asd</fullName>
                </value>
                <value>
                    <fullName>sdf</fullName>
                </value>
                <value>
                    <fullName>dfg</fullName>
                </value>
                <value>
                    <fullName>fgh</fullName>
                </value>
                <value>
                    <fullName>ghj</fullName>
                </value>
                <value>
                    <fullName>hjk</fullName>
                </value>
                <value>
                    <fullName>jkl</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Head_Of_Company_Title__c</fullName>
        <label>Head Of Company Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>a</fullName>
                </value>
                <value>
                    <fullName>b</fullName>
                </value>
                <value>
                    <fullName>c</fullName>
                </value>
                <value>
                    <fullName>d</fullName>
                </value>
                <value>
                    <fullName>e</fullName>
                </value>
                <value>
                    <fullName>f</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Head_Of_Company__c</fullName>
        <label>Head Of Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Category__c</fullName>
        <label>Job Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Sr.Developer</fullName>
                </value>
                <value>
                    <fullName>jr.Developer</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Number_of_Years_in_Business__c</fullName>
        <label>Number of Years in Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-5</fullName>
                </value>
                <value>
                    <fullName>5-10</fullName>
                </value>
                <value>
                    <fullName>10-15</fullName>
                </value>
                <value>
                    <fullName>Greater Than 15</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>PostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mr.</fullName>
                </value>
                <value>
                    <fullName>Mrs.</fullName>
                </value>
                <value>
                    <fullName>Miss.</fullName>
                </value>
                <value>
                    <fullName>Dr.</fullName>
                </value>
                <value>
                    <fullName>Prof.</fullName>
                </value>
                <value>
                    <fullName>Ms.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>website__c</fullName>
        <label>website</label>
        <type>Url</type>
    </fields>
    <label>Partner_request</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Partner_request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/classes/AllPrCtrl.cls
public class AllPrCtrl{

     @AuraEnabled
    public static void  updatePr(Partner_request__c  passedPr){


        update passedPr;
    }



     @AuraEnabled
    public static List<Partner_request__c> AllPrs(){


        return [select id,Name,First_Name__c,Last_Name__c,Email__c from Partner_request__c order by Name ASC];
    }
    
    
    @AuraEnabled
    public static Partner_request__c PrData(String Prid){


        return [select id,Address1__c,
                       City__c,Company__c,Country__c,
                       Email__c,First_Name__c,Form_Of_Organization__c,
                       Head_Of_Company__c,Head_Of_Company_Title__c,
                       Job_Category__c,Job_Title__c,Last_Name__c,Mobile__c,
                       Number_of_Years_in_Business__c,Phone__c,PostalCode__c,
                       Salutation__c,State__c,website__c 
                       ,Accoutn_Created__c,Business_Acceptence__c
                       ,Duplicate_Check__c,Completed__c  from Partner_request__c where id=:Prid];
    }

}