MyOrg/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/objects/Partner_request__c.object
<CustomObject>
    <fields>
        <fullName>Accoutn_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accoutn Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Acceptence__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Acceptence</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner_requests</relationshipLabel>
        <relationshipName>Partner_requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Duplicate Check</label>
        <type>Checkbox</type>
    </fields>
    <label>Partner_request</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Partner_request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/classes/PartnerRequestJ.cls
public class PartnerRequestJ {
     
    Public List <Partner_request__c> partnerrec {get;set;}
    
    
   public PartnerRequestJ(){
        partnerrec = new List <Partner_request__c>();
        
       partnerrec =  [SELECT Accoutn_Created__c,Address1__c,Business_Acceptence__c,City__c,Company__c,Completed__c,ConnectionReceivedId,ConnectionSentId,Country__c,CreatedById,CreatedDate,Duplicate_Check__c FROM Partner_request__c LIMIT 100];
    }
     
 

}