MyOrg/src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>AMERICAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/objects/Fields_Config__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Fields Config</relationshipLabel>
        <relationshipName>Fields_Config</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>FieldName</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salutationis</fullName>
                </value>
                <value>
                    <fullName>firstNameis</fullName>
                </value>
                <value>
                    <fullName>Lastnameis</fullName>
                </value>
                <value>
                    <fullName>jobCategoryis</fullName>
                </value>
                <value>
                    <fullName>jobtitleis</fullName>
                </value>
                <value>
                    <fullName>Address1is</fullName>
                </value>
                <value>
                    <fullName>Cityis</fullName>
                </value>
                <value>
                    <fullName>stateis</fullName>
                </value>
                <value>
                    <fullName>PostalCodeis</fullName>
                </value>
                <value>
                    <fullName>Phoneis</fullName>
                </value>
                <value>
                    <fullName>MobilePhoneis</fullName>
                </value>
                <value>
                    <fullName>Emailis</fullName>
                </value>
                <value>
                    <fullName>Companyis</fullName>
                </value>
                <value>
                    <fullName>HeadoftheCompanyis</fullName>
                </value>
                <value>
                    <fullName>HeadoftheCompanyTitleis</fullName>
                </value>
                <value>
                    <fullName>FormofOrganizationis</fullName>
                </value>
                <value>
                    <fullName>Websiteis</fullName>
                </value>
                <value>
                    <fullName>Numberofyearsinbusinessis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tab__c</fullName>
        <label>Tab</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Partner_sectionTab</fullName>
                </value>
                <value>
                    <fullName>ContactTab</fullName>
                </value>
                <value>
                    <fullName>CompanyTab</fullName>
                </value>
                <value>
                    <fullName>FocusTab</fullName>
                </value>
                <value>
                    <fullName>SegmentTab</fullName>
                </value>
                <value>
                    <fullName>ServiceTab</fullName>
                </value>
                <value>
                    <fullName>CompleteTab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isMandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMandatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isRequired</label>
        <type>Checkbox</type>
    </fields>
    <label>Fields Config</label>
    <nameField>
        <displayFormat>FC-{00000}</displayFormat>
        <label>Fields Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fields Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/objects/Partner_request__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner_requests</relationshipLabel>
        <relationshipName>Partner_requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner_request</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Partner_request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/classes/myDynamicForm.cls
public class myDynamicForm{

              
              public static map<String,Country__c>   CountryIdMap = new map<String,Country__c>( [select id,Region__c,Name from Country__c ]);
              
              
               @AuraEnabled
               public String mydata{get;set;}  
                public myDynamicForm(){
                
              
                
                }
             @AuraEnabled
             public static list<Country__c> Allcountries(){
             System.debug('>   > '+CountryIdMap.values());
             
             return CountryIdMap.values();
             }
            
            @AuraEnabled
            public static List<filedConfig> getFields(String SelectedCountryId){
               list<filedConfig> AllFields = new List<filedConfig>();
               
               
               try{
               list<Fields_Config__c> FieldsConfigforSelCountry = [select id,name,
                                                                          FieldName__c,
                                                                          isMandatory__c,
                                                                          isRequired__c,
                                                                          Country__r.Name,
                                                                          Tab__c
                                                                          from Fields_Config__c 
                                                                          where Country__r.id=:SelectedCountryId ];
            
         
            //contact Tab
            for(Fields_Config__c fc:FieldsConfigforSelCountry ){
                AllFields.add(new filedConfig(fc.FieldName__c,fc.isRequired__c,fc.isMandatory__c,fc.Tab__c));
                }
                }catch(Exception ex){
                System.debug('>>>>> exception occured '+ex);
                }
            
            
            return AllFields;
            
            }
            
            
            
            @AuraEnabled
            
            public static String savePr(Partner_request__c userPr){
            
            System.debug('>>>>>>> Passed Pr is '+userPr.Country__c);
            userPr.Country__c = userPr.Country__c;
            Insert userPr;
            
            return  [select name from Partner_request__c where id=:userPr.id].name;
            }
            
            
            
            
            public class filedConfig{
                @AuraEnabled
                public String FieldLabel;
                @AuraEnabled
                public String FieldType;
                @AuraEnabled
                public Boolean isRequired;
                 @AuraEnabled
                public String fieldId;
                @AuraEnabled
                public Boolean isMandatory;
                 @AuraEnabled
                public String Tabis;
                
                public filedConfig(String FieldLabel,String FieldType,boolean isRequired,String fieldId){
                
                    this.FieldLabel = FieldLabel;
                    this.FieldType = FieldType;
                    this.isRequired = isRequired;
                    this.fieldId = fieldId;
                }
                
                public filedConfig(String FieldLabel,boolean isRequired,boolean isMandatory,String Tabis){
                
                    this.FieldLabel = FieldLabel;
                    this.isRequired = isRequired;
                    this.isMandatory = isMandatory;
                    this.Tabis = Tabis;
              
                }
            
            }




}