MyOrg/src/objects/DemoForm__c.object
<CustomObject>
    <label>DemoForm</label>
    <nameField>
        <displayFormat>Df-{0000}</displayFormat>
        <label>DemoForm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DemoForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/objects/Form_Responce__c.object
<CustomObject>
    <fields>
        <fullName>DemoForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DemoForm</label>
        <referenceTo>DemoForm__c</referenceTo>
        <relationshipLabel>Form Responces</relationshipLabel>
        <relationshipName>Form_Responces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>responce__c</fullName>
        <label>responce</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Form Responce</label>
    <nameField>
        <displayFormat>FR-{0000}</displayFormat>
        <label>Form Responce Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Responces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyOrg/src/classes/AnswersParserCtrl.cls
public with sharing class AnswersParserCtrl {

public list<list<AnswersParser>> AllAnswers {get;set;} 

 list<AnswersParser> EachResp {get;set;}

    public AnswersParserCtrl (){
   AllAnswers  =  new list<list<AnswersParser>> ();
   for(Form_Responce__c EachAns : [select id,DemoForm__c,responce__c From Form_Responce__c Where DemoForm__c = : apexpages.currentpage().getparameters().get('id')]){
   
          List<String> EachQuestionResponse = EachAns.responce__c.split('#123');
          
          EachResp = new list<AnswersParser>();
          for(String s:EachQuestionResponse){
          EachResp.add(AnswersParser.parse('{'+s.replaceAll('\n','').replaceAll('\r','')+'}'));
          
          }
   
   AllAnswers.add(EachResp );
   
   }
    
   
    }
    
    
}